routes/Beheerder/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required
from models import Beheerder
from extensions import db
from routes.Beheerder.form import BeheerderForm

Beheerder_bp = Blueprint('Beheerder', __name__, template_folder='templates')

@Beheerder_bp.route('/')
@login_required
def index():
    Beheerders = Beheerder.query.order_by(Beheerder.naam).all()
    return render_template('Beheerder/index.html', Beheerders=Beheerders)

@Beheerder_bp.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = BeheerderForm()
    if form.validate_on_submit():
        WeetjeCreated = Beheerder(naam=form.naam.data, gender=form.gender.data)
        db.session.add(WeetjeCreated)
        db.session.commit()
        flash('Weetje toegevoegd!', 'success')
        return redirect(url_for('Beheerder.index'))
    return render_template('Beheerder/form.html', form=form, title='Beheerder toevoegen')

@Beheerder_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    Weetje1 = Beheerder.query.get_or_404(id)
    form = BeheerderForm(obj=Weetje1)
    if form.validate_on_submit():
        Weetje1.naam = form.naam.data
        Weetje1.gender = form.gender.data
        db.session.commit()
        flash('Weetje bijgewerkt!', 'success')
        return redirect(url_for('Beheerder.index'))
    return render_template('Beheerder/form.html', form=form, title='Beheerder bewerken')

@Beheerder_bp.route('/delete/<int:id>', methods=['POST'])
@login_required
def delete(id):
    Weetje1 = Beheerder.query.get_or_404(id)
    db.session.delete(Weetje1)
    db.session.commit()
    flash('Beheerder verwijderd!', 'success')
    return redirect(url_for('Beheerder.index'))

templates/Beheerder/form.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ title }}</h1>
<form method="post">
  {{ form.hidden_tag() }}
  <div class="mb-3">
    {{ form.naam.label }} {{ form.naam(class="form-control") }}
  </div>
  <div class="mb-3">
      {{ form.gender.label }} {{ form.gender(class="form-control") }}
  </div>
  <button type="submit" class="btn btn-primary">{{ form.submit.label }}</button>
</form>
{% endblock %}

templates/Beheerder/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Beheerder</h1>
<a href="{{ url_for('Beheerder.add') }}" class="btn btn-primary mb-3">Beheerder toevoegen</a>
<ul>
  {% for Beheerder in Beheerders %}
  <li>{{ Beheerder.naam }}
    <a href="{{ url_for('Beheerder.edit', id=Beheerder.id) }}">Bewerken</a>
    <form action="{{ url_for('Beheerder.delete', id=Beheerder.id) }}" method="post" style="display:inline;">
      <button type="submit" class="btn btn-link">Verwijderen</button>
    </form>
  </li>
  {% endfor %}
</ul>
{% endblock %}